### ISSUE TITLE
Trouble building

### ISSUE THREAD

**Issue by justinmchase** [mumble-voip/libmumble-legacy#3]
What is the status of this project? Do you  have binaries published anywhere?

I would like to evaluate the possible usage of this project inside of an electron application. I have been using `node-mumble` but haven't been able to really get it to work. Running test.bat doesn't seem to be working for me as is. 

```
  5>E:\code\libmumble\test\3rdparty\opensslbuild\libcrypto.vcxproj(15,3): error MSB4019: The imported project "C:\Pr
    ogram Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.Default.props" was not found. Confirm that the path i
    n the <Import> declaration is correct, and that the file exists on disk.
```

Which is indeed missing, though I don't know why it missing nor why it's looking for a file in that location.

**Comment by mkrautz** [comment]
libmumble is a work in progress.

Right now, the only API it exposes is this: https://github.com/mumble-voip/libmumble/tree/master/include/mumble

So, no Mumble functionality yet.

Also note that test.bat requires MSVC 2013. Not sure if that's what you're building with?
(See https://github.com/mumble-voip/libmumble/blob/master/test.bat)
